---
title: "Getting lyrics with Genius API"
format: 
    html: 
        toc: true
        toc-title: 'Steps'
        theme: 'flatly'
execute:
  echo: true
  warning: false
---

# Setup

## Load Libraries

```{r}
library(geniusr)
library(tidyverse)
```

## Load Songs

```{r}
hh_songs <- read_csv('../data/top_rap_songs_89-19.csv')|> 
    mutate(across(everything(),
                  str_remove_all,
                  '\"'),
           across(everything(),
                  str_remove,
                  '\\n'),
           rel_date = lubridate::mdy(date)) |>
    mutate(song = str_remove_all(song,
                                  '↑') |> 
                        str_trim('right')) |>
    separate(artist, 
             into = c("artist","features"),
             fill = "right",
             sep="featuring ") |> 
    select(song, artist, rel_date) |> 
    mutate(hip_hop_rnb = 1)

hh_songs
```

```{r}
rnb_songs <- read_csv('../data/rnb_89-99.csv') |> 
    select(song, artist) |> 
    mutate(hip_hop_rnb = 1) |> 
    distinct(artist, song,hip_hop_rnb) 

songs <- rnb_songs |> 
    bind_rows(hh_songs)

songs |> write_csv('../data/songs.csv')


songs
```

# Get Lyrics

## Query Genius API

```{r eval=FALSE}
art_songs_df <- songs |>
    rowwise() |>
    mutate(artist_id = search_artist(search_term = artist,
                                  n_results = 3) |>
               arrange(artist_id) |>
               head(1) |>
               pull(artist_id),
           song_id  = search_song(search_term = song,
                                 n_results = 3) |>
               arrange(song_id) |>
               head(1) |>
               pull(song_id)
       )
 
art_songs_df
```

```{r }

art_sng_lyr_df <- songs |>
    rowwise() |>
    mutate(
        tryCatch(
            get_lyrics_search(
                artist_name = artist,
                song_title  = song
                ) |>
                summarise(
                    lyrics  = str_c(line,
                                    collapse = " ")
                    ),
            error = function(w)
                return(NA)
            ) 
       ) |> 
    unnest(lyrics) |> 
    select(song, artist, rel_date,lyrics)
 
art_sng_lyr_df |> write_csv('../data/art_sng_lyr_df.csv')
```

```{r include=FALSE}

art_sng_lyr_df <- read_csv('../data/art_sng_lyr_df.csv')

art_sng_lyr_df
```

```{r echo=FALSE}
lyrics_df <- art_sng_lyr_df |> 
    unnest(lyrics) |> 
    select(song, artist, rel_date,lyrics)

lyrics_df
```

```{r include=FALSE}
lyrics_df |> write_rds('../data/lyrics_df.rds')
```
